trigger:
  branches:
    include:
      - main
      - development

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'

- script: |
    python -m pip install --upgrade pip
    python -m pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pylint calculator_app 
  displayName: 'Static analysis (pylint)'

- script: |
    pytest --cov=calculator_app --cov-report=xml --cov-fail-under=80
  displayName: 'Run unit tests with coverage'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: 'coverage.xml'
    pathToSources: 'calculator_app'
  displayName: 'Publish coverage report'
